#%RAML 1.0
types:
  RequestDataType:
    properties:
      post_id:
        example: "2003"
        type: string
  ResonseDataType:
    properties:
      Userdetails:
        items:
          properties:
            post_id:
              example: "2003"
              type: string
            id:
              example: "1978"
              type: string
            name:
              example: Bhaaswar Pothuvaal III
              type: string
annotationTypes:
  NewGroup:
    type: any
title: IE-Major-Sangram-Kishore-Swain
mediaType:
  - application/json
version: v1
protocols:
  - HTTP
/Milestone3:
  post:
    body:
      type: RequestDataType
    responses:
      "201":
        body:
          type: RequestDataType
(NewGroup):
  name: Group
  description: Group annotation
